#!/usr/bin/env ruby

require 'inertia'

Inertia.configure do |config|
  config.ignore_scss = ARGV.include?('--ignore-scss')
  config.ignore_js = ARGV.include?('--ignore-js')
  config.ignore_jsx = ARGV.include?('--ignore-jsx')
  config.ignore_ts = ARGV.include?('--ignore-ts')
  config.ignore_tsx = ARGV.include?('--ignore-tsx')
  config.ignore_haml = ARGV.include?('--ignore-haml')
  config.ignore_rabl = ARGV.include?('--ignore-rabl')
  config.ignore_erb = ARGV.include?('--ignore-erb')
  config.ignore_ruby_spec = ARGV.include?('--ignore-ruby-spec')
  config.ignore_yml = ARGV.include?('--ignore-yml')
end

Inertia::Resistance.display
